config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit; end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
  </head>
  <body class="card p-3">
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <div class="mb-3">
    <%= f.label :title %>
    <%= f.text_field :title %>
    <div class="mb-3">
      <%= f.label :details %>
      <%= f.text_field :details %>
      <div class="mb-3">
        <%= f.submit %>
      <% end %>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= render "form", task: @task %>
<br>
<%= link_to 'Back to list', tasks_path %>

app/views/tasks/index.html.erb
<div>
  <h1>My Tasks</h1>
  <br>
  <% @tasks.each do |task| %>
    <ul class="fa-ul">
      <li>
        <i class="fa-li fa fa-check-square"></i>
        <i class="far fa-square"></i>
        <%= link_to task.title, task_path(task) %> -
        <%= link_to task_path(task), method: :delete, data: { confirm: "Are you sure?" } do %>
          <i class="far fa-trash-alt"></i>
        <% end %>
      </li>
    </ul>
  <% end %>
  <br>
  <%= link_to 'Add a new task', tasks_new_path %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= render "form", task: @task %>
<br>
<%= link_to 'Back to list', tasks_path %>

app/views/tasks/show.html.erb
<h1>My Tasks</h1>
<p><%= @task.title %></p>
<p><%= @task.details %></p>
<%= link_to 'Edit', edit_path(@task) %>
<br>
<%= link_to 'Go Back', tasks_path %>